### ISSUE TITLE
Activation Issue

### ISSUE THREAD

**Issue by JtLively** [creativecommons/creativecommons-wordpress-plugin#17]
I tried to activate the plugin and got the following error: 
Parse error: syntax error, unexpected '.', expecting ',' or ';' in /home4/_user_/public_html/wp-content/plugins/wordpress-plugin-awesome/includes/ccbutton.php on line 8

I replaced "." with "," and removed some a few ''s and then got errors involving Line 13 and then the following error:
Parse error: syntax error, unexpected '<' in /home4/jjsprat/public_html/wp-content/plugins/wordpress-plugin-awesome/includes/ccbutton.php on line 5

**Comment by cogdog** [comment]
I'm seeing same error in the `awesome` branch version. The "." is correct, but I am stumped to figure out what is wring with the string, everything looks constructed well to me. Pinging Rob.

**Comment by cogdog** [comment]
Doh. There is no need for the string concatenation. This works:

```
    const CC_BUTTON_TAIL = '"><span data-l10n-id="Share">Share</span></button>
<div class="cc-dropdown-wrapper"><button class="cc-attribution-format-select">HTML &#x25BC;</button>
<ul class="cc-dropdown-menu" aria-haspopup="true" aria-expanded="false">
    <li class="cc-dropdown-menu-item cc-dropdown-menu-item-selected"><a class="cc-dropdown-menu-item-link cc-format-html-rdfa" data-cc-format="html-rdfa" href="#">HTML</a></li>
    <li class="cc-dropdown-menu-item"><a class="cc-dropdown-menu-item-link cc-format-text" data-cc-format="text" href="#">Text</a></li></ul></div>
<button class="cc-attribution-help-button" data-l10n-id="?">?</button></div>';
```
Will submit.

**Comment by JtLively** [comment]
Should I try this plugin again for testing or do yall have all the testing done?

**Comment by robmyers** [comment]
I've merged cogdog's contribution. There may be another round of development soon...
