### ISSUE TITLE
Home Page Attribution is for last item in loop

### ISSUE THREAD

**Issue by cogdog** [creativecommons/creativecommons-wordpress-plugin#47]
It might by my whacky theme, but the attribution listed is not the general one for the site, but the last post in the loop:

http://cogdogblog.com/

It does work for archives
http://cogdogblog.com/category/photo/
http://cogdogblog.com/tag/attribution/

**Comment by ahmadbilaldev** [comment]
Fixed with the addition of Gutenberg blocks. See [Issue #7](https://github.com/creativecommons/creativecommons-wordpress-plugin/issues/7).
