### ISSUE TITLE
Missing "license" at end

### ISSUE THREAD

**Issue by cogdog** [creativecommons/creativecommons-wordpress-plugin#49]
For some reason, on a second test site http://barkingdog.me the text for the license link drops the word "License" leaving an incomplete sentence. Saw same thing for using BY and BY-SA

![missing license](https://cloud.githubusercontent.com/assets/463038/22121536/bf7f5d60-de41-11e6-8330-464b17f7eb97.jpg)

**Comment by brijn1975** [comment]
also my samsung android was hacked inguess over two years ago. my phone was controlled better and faster then i could keep up.  i turned off the phone for many months and thought it was gone but it came back with a vengeance.  they even dropped all playstore apps when inclined.  i got the apple as a fix but things are just as crazy.  ive taken so many screenshots of proof but appls does nothing.  dont even look.  they want video now.  i could go on all day the sophistication of the ability whomever has with what i have seen and desl with.  anyone with advice, im all ears

**Comment by ahmadbilaldev** [comment]
Fixed in [PR #59](https://github.com/creativecommons/creativecommons-wordpress-plugin/pull/59).
