### ISSUE TITLE
Compare lumen's CC plugin on candela (built on WP)

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/creativecommons-wordpress-plugin#8]
Review, then incorporate any improvements to our plugin, suggest changes to theirs, etc.

https://github.com/lumenlearning/candela

**Comment by BjornW** [comment]
Hi @janeatcc I did not see any CC License like plugin in the repo you linked. I'm probably overlooking something?

**Comment by janeatcc** [comment]
Hi @BjornW - maybe it's not the same as this plugin, but CC license + PD selection is in there. 

See https://github.com/lumenlearning/candela-vagrant/blob/master/tests/update-book.html
and https://github.com/lumenlearning/candela/pull/105 for example. 

If it's not the same thing we can move this issue out of this WP plugin repo and into platform-initiative

**Comment by BjornW** [comment]
Hi Jane, the stuff we might be interested in can be found in the candela-citation plugin. Although their approach is quite different from ours. For instance they are not using CC HQ's license chooser and instead use license data supplied with the plugin.

**Comment by ahmadbilaldev** [comment]
The Lumen's plugin has been deprecated and is no longer maintained.
